apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: org-hyperscheduler
  annotations:
    github.com/project-slug: dmitrym0/org-hyperscheduler
    backstage.io/techdocs-ref: dir:.
    circleci.com/project-slug: github/dmitrym0/org-hyperscheduler
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: other
  lifecycle: unknown
  owner: guests
