apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: org-hyperscheduler
  annotations:
    github.com/project-slug: dmitrym0/org-hyperscheduler
  annotations:
    backstage.io/techdocs-ref: value
spec:
  type: other
  lifecycle: unknown
  owner: guests
